### ISSUE TITLE
Finalize Adapter/Mapper API and implementations

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#1365]
# Overview

Since v5, the framework uses new Adapter/Mapper architecture replacing legacy Storage API. It splits static metadata conversion (Mapper) and actual service manipulations (Adapter).

# Plan

- [x] review and incorporate @ezwelty comment - https://github.com/frictionlessdata/framework/pull/862#issuecomment-1323862577 (changes / bug fixes)
- [x] rebase static mapping on separate package - > https://github.com/frictionlessdata/frictionlessdata.io/issues/784?
- [x] Remove database_url parts from SqlControl?
- [x] Mappers should not accept any init parameters? - no
- [x] finalize Adapter API
- [x] finalize Mapper API
- [x] extract static ZenodoMapper -> https://github.com/frictionlessdata/frictionlessdata.io/issues/784
- [x] extract static CkanMapper (frictionless-ckan-mapper lib based?) -> https://github.com/frictionlessdata/frictionlessdata.io/issues/784
