### ISSUE TITLE
Improve the CLI functionality and documentation

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/frictionless-py#175]
# Overview

This issue contains CLI improvements

# Tasks

- [ ] support `headers` options
- [ ] support granular check options
- [ ] support providing validation config instead of options (like stringified json) 

---

My guess would be:

```
goodtables --checks "{'duplicate-row': True}" datapackage datapackage.json 
```

But it returns:

```
goodtables.exceptions.GoodtablesException: Checks filter "{'duplicate-row': True}" is not supported
```

---

__from @aborruso__

Hi,
in the cli there are this options:

- --checks
- --error-limit
- --infer-schema/--no-infer-schema
- --json
- --order-fields
- --output
- --preset
- --quiet
- --row-limit
- --schema
- --skip-checks
- --table-limit

But I do not find any documentation here and if I write `goodtables --help` I have only the text below.

I could try to help with a PR, reading the cli.py code.

Thank you

```
Usage: goodtables [OPTIONS] COMMAND [ARGS]...

  Tabular files validator.

  There are two categories of validation checks available:

  * Structural checks: ensure there are no empty rows, no blank headers,
  etc.

  * Content checks: ensure the values have the correct types (e.g. string),
  their format is valid (e.g. e-mail), and they respect some constraint
  (e.g. age is greater than 18).

  Full documentation at: <https://github.com/frictionlessdata/goodtables-py/>

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  validate*  Validate tabular files (default).
  init       Init data package from list of files.
```

**Comment by roll** [comment]
@danfowler 
For now this CLI parameter only supports:
- all
- schema
- structure

But custom inspector could be used to achieve the goal. 

---

I've renamed this issue to make it feature request.

**Comment by roll** [comment]
MERGED #186

**Comment by roll** [comment]
MERGED with #386
