### ISSUE TITLE
Improve CLI

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#386]
# Overview

For now, we have CLI as a basic wrapper over the main functionality. It can be made much better for the overall end-user experience.

# Tasks

- [x] rebase on Typer
- [x] provide auto-completion
- [x] limit default amount of rows for extract? - MOVED to #508
- [x] support stdin/stdout comprehensively (see #326)
- [x] an ability to extract data in CSV format
- [ ] write functional tests

**Comment by roll** [comment]
> From @khughitt

But more seriously, perhaps a better/much simpler solution would be to just have frictionless default to only printing the top N rows of data?

This is similar to how R/Pandas/Julia print matrices and dataframes to the screen.

You could similarly limit the number of columns displayed by default to make it more readable. If you could detect the terminal width, then the exact number could probably be optimized.

An option could then be included (e.g. --num-rows) to allow the user to override the default, with "0" indicating that all rows should be rendered.

Just a thought..

Thanks again for the help on discord! It is much appreciated.

Cheers,
Keith
