### ISSUE TITLE
Implement parser.schema and reuse storages

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#396]
# Overview

For some formats, parsers should be able to provide a schema information e.g. SQL. As an option, it can be a stream frontmatter containing schema, dialect etc. The second part is rebaseing some parser functionality on storages e.g. for SQL.

# Tasks

- [x] implement parser.schema
- [x] rebase some functionality on `Storage`?
- [x] ensure that `sqlParser.write` uses proper types instead of strings
