### ISSUE TITLE
Write SQL/Pandas/SPSS/BigQuery/etc guides

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#401]
# Overview

When all the plugins migration is done we need to write `Working with X` guides for every integration.

# Tasks
- [x] mark bigquery/spss experimental
- [x] add support for `resource/package.to_sql(connection_string)` - now only sa.engine is supported
- [x] mention database support level (core: pg/sqlite/mysql)
- [x] write guides

**Comment by roll** [comment]
DONE
