### ISSUE TITLE
Advance SQL plugin to the stable state

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#405]
# Overview

The SQL Plugin is in the experimental state ATM.

# Tasks

- [ ] Speed up SQL export using COPY command - https://stackoverflow.com/a/24150855
- [ ] Warnings/documentation on not supported functionality
- [ ] Add timezone support if/where possible
- [ ] Write more tests (edge cases)
- [ ] TBD

**Comment by peterdesmet** [comment]
Regarding timezone support: would be nice if timestamps with UTC offsets (e.g. `+02:00`) are automatically converted to UTC if offsets are not supported in that database (e.g. in SQLite). See https://github.com/frictionlessdata/datapackage-pipelines-sql-driver/issues/89 for original issue.

**Comment by roll** [comment]
Since v5 we consider it's stable and will be working on it based on incoming bug reports and feature requests

- https://github.com/frictionlessdata/frictionless-py/issues/1102
- https://github.com/frictionlessdata/frictionless-py/issues/1087

**Comment by dafeder** [comment]
Hi @roll - trying to understand how one would use the fast export/copy feature. Is this somewhere in the documentation that I'm missing?

**Comment by roll** [comment]
Hi @dafeder,

I continued working on `frictionless index` in https://github.com/frictionlessdata/framework/issues/1087 (I'll ping you next week when the preview is read)
