### ISSUE TITLE
Advance BigQuery plugin to the stable state

### ISSUE THREAD

**Issue by micimize** [frictionlessdata/frictionless-py#411]
# Overview

For now, bigquery support is experimental as the implementation is not solid enough.

# Tasks
- [ ] can reading be streaming?
- [ ] wait writing jobs in parallel?
- [ ] rebase on google-cloud-bigquery library
- [ ] provide a proper sorting solution for reading
- [ ] make it work for other locations (it can't find a job if it's not in the US)
- [ ] implement support of constraints if possible
- [ ] add support for date/times with timezone
- [ ] rebase testing on vcr.py?

---

as per [api-client-library's suggestion](https://developers.google.com/api-client-library/python/apis/bigquery/v2):
> While this library is still supported, we suggest trying the newer Cloud Client Library for BigQuery, especially for new projects. See BigQuery Libraries for installation and usage details.

**Comment by roll** [comment]
Since v5 we consider it's stable and will be working on it based on incoming bug reports and feature requests
