### ISSUE TITLE
Clean up the codebase

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#447]
# Tasks

- [x] process "NOTE"s
- [x] move big data files to some other repo
- [x] recover skipped tests
- [ ] Consider `loader.byte_sample/text_sample` and proper sample caching/chain (less requests)
- [ ] Unify source detection like Resource(source)
- [ ] Deprecate Table/File
- [ ] Merge Table/File tests to Resource
- [ ]  Add from/to_csv/etc aliases to resource?
- [ ] Remove `validate_inqury` (and use `validate_package` instead)?
- [ ]  Reshape control/dialect/query/infer (header to query/detect_encoding?)
- [ ]  Review outstanding NOTE/TODOs in the repo
- [ ]  Sync checks/steps and/with error/types!?
- [ ]  Finalize error group names; Сheck's API
- [ ]  Make documentation hierarchical (use .build/tutorials)?
- [ ]  Plugins priority (or prepare/create_resource)!
- [ ]  Rework extract/validate API accepting resource/package??
- [ ]  Report should have resource property for tables instead of schema/dialect/etc?
- [ ] process "TODO"s
- [ ] Remove deprecated code for version 4 (table/file)
- [ ]  Add Package/Resource/Schema/Field guides
- [ ]  Remove notebook sources from git?
- [ ]  Fix coverage to codecov sending?
- [ ] coverage -> 90%

**Comment by roll** [comment]
DONE in #607 #613 #621 and others
