### ISSUE TITLE
Integration with ElasticSearch

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#473]
# Overivew

We had an implementation for `tableschema.Storage` here - https://github.com/frictionlessdata/datapackage-pipelines-elasticsearch-driver. Also, I started a migration but didn't go too far here - https://github.com/frictionlessdata/frictionless-py/blob/a833f59a90a50e1d5004144a1683be5ea9d5f896/frictionless/plugins/elastic.py.

As far as I understand, it doesn't implement the storage interface the same way (required to work with Resource/Package) as other plugins (sql/ckan/etc) do.

# Tasks
- [ ] understand what is the difference in mapping between es implementation and others
- [ ] using existent code migrate to `frictionless.Storage` updating the way we map resources
- [ ] make it work with the latest ElasticSearch versions (server and library)
- [ ] write functional tests based on the Sql/Pandas/etc template
