### ISSUE TITLE
Advance Pandas plugin to the stable stage

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#563]
# Overview

The Pandas Plugin is in the experimental state ATM.

# Tasks

- [ ] Warnings/documentation on not supported functionality
- [ ] Add timezone support if/where possible
- [ ] Write more tests (edge cases)
- [ ] TBD

**Comment by roll** [comment]
Since v5 we consider it's stable and will be working on it based on incoming bug reports and feature requests
