### ISSUE TITLE
Resource/Package don't expose all standard properties

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#587]
# Overview

E.g. this will fail:
- `Package(name='abcedf', keywords=['meep', 'beep', 'boop'], version='1.0.0')` 
- `package.version`

# Tasks
- [x] Identify discrepancies between the specs and the framework
- [x] Add constructor arguments and instance properties
- [x] Add `field.rdf_type` (#599)
