### ISSUE TITLE
Improve test coverage for Windows

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#590]
# Overview

In #589 we added Windows testing on CI/CD but we disabled some tests because of a few groups of problems Frictionless has described below

# Tasks

- [ ] Fix bytes/hash
- [ ] Fix os.relpath
- [ ] Fix tmp permission
- [ ] Fix slash/backslash
- [ ] Fix other problems
- [ ] Rebase from `make test` to `make test-ci` (remote/databases/etc)

# Note

Github Actions for MacOS/Windows doesn't support external services like databases so probably we need some external service like a free Heroku database.
