### ISSUE TITLE
Improve tutorials/references sections

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#688]
# Overview

We need to improve it, in general, filling some blank docstrings etc

# Tasks

- [ ] test/proo-read all the tutorials
- [ ] improve API reference
- [ ] fix checks/steps in API reference (lower-case)
- [ ] improve other references
