### ISSUE TITLE
Finish the Frictionless Cars notebook and link it from the site

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionless-py#735]
# Overview

It needs to be finished

# Tasks

- [ ] rebase on GDP per capita
- [ ] read/show raw resource before transformations
- [ ] implement and use `steps.rename_resource/field` (or update with `new_name`)
- [ ] add text paragraphs
- [ ] add zip export

**Comment by roll** [comment]
DONE in f24a583
